# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tL59abKFNR1Y8eki-JV8Y8r-bl15UomV
"""

!pip install pandas scikit-learn openpyxl flask

import pandas as pd

# Load dataset
df = pd.read_excel("ai_triage_queue_dataset_200.xlsx")

# View data
df.head()

import os
os.getcwd()

os.listdir()

import pandas as pd

# Load dataset
df = pd.read_excel("/content/sample_data/ai_triage_queue_dataset_200.xlsx")

# View data
df.head()

X = df[["Medical_History","Symptoms","Keyword_Symptoms"]]
y = df["AI_Urgency"]

from sklearn.feature_extraction.text import TfidfVectorizer

# Combine text columns
df["Text"] = (
    df["Medical_History"] + " " +
    df["Symptoms"] + " " +
    df["Keyword_Symptoms"]
)

vectorizer = TfidfVectorizer()
X_vector = vectorizer.fit_transform(df["Text"])

# Replace missing values with empty string
df = df.fillna("")

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Load file
df = pd.read_excel("ai_triage_queue_dataset_200.xlsx")

# Clean missing values
df = df.fillna("")

# Create text column
df["Text"] = (
    df["Medical_History"].astype(str) + " " +
    df["Symptoms"].astype(str) + " " +
    df["Keyword_Symptoms"].astype(str)
)

# TF-IDF
vectorizer = TfidfVectorizer()
X_vector = vectorizer.fit_transform(df["Text"])

print("Vector shape:", X_vector.shape)

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Load file
df = pd.read_excel("/content/sample_data/ai_triage_queue_dataset_200.xlsx")

# Clean missing values
df = df.fillna("")

# Create text column
df["Text"] = (
    df["Medical_History"].astype(str) + " " +
    df["Symptoms"].astype(str) + " " +
    df["Keyword_Symptoms"].astype(str)
)

# TF-IDF
vectorizer = TfidfVectorizer()
X_vector = vectorizer.fit_transform(df["Text"])

print("Vector shape:", X_vector.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vector, y, test_size=0.2, random_state=42
)

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

def predict_disease(symptoms):

    s = symptoms.lower()

    if "chest pain" in s:
        return "Heart Disease"

    if "severe headache" in s or "blurred vision" in s:
        return "Neurological Issue"

    if "thirst" in s and "urination" in s:
        return "Diabetes"

    if "cough" in s and "night sweats" in s:
        return "Tuberculosis"

    if "wheezing" in s:
        return "Asthma"

    if "headache" in s:
        return "Migraine"

    return "General Illness"

def ai_triage(history, symptoms, keywords):

    # Prepare text
    text = history + " " + symptoms + " " + keywords

    # Vectorize
    text_vec = vectorizer.transform([text])

    # Predict urgency
    urgency = model.predict(text_vec)[0]

    # Predict disease
    disease = predict_disease(symptoms)

    return urgency, disease

u, d = ai_triage(
    "Migraine",
    "severe headache blurred vision",
    "headache,vision"
)

print("Urgency:", u)
print("Disease:", d)

from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route("/predict", methods=["POST"])
def predict():

    data = request.json

    history = data["history"]
    symptoms = data["symptoms"]
    keywords = data["keywords"]

    urgency, disease = ai_triage(history, symptoms, keywords)

    return jsonify({
        "urgency": urgency,
        "disease": disease
    })

app.run()