-- database/migrations/009_smart_nurse_features.sql

-- 1. Nurse Tasks Table (Task Board)
CREATE TABLE IF NOT EXISTS nurse_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    nurse_id BIGINT REFERENCES staff(id), -- Assuming staff table exists
    task_name TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);

-- 2. Nurse Records (Vitals & EWS)
-- We use CREATE TABLE IF NOT EXISTS to be safe, as it might not exist.
CREATE TABLE IF NOT EXISTS nurse_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    nurse_id BIGINT REFERENCES staff(id),
    blood_pressure TEXT, -- e.g. "120/80"
    pulse INTEGER,
    temperature DECIMAL(5,2),
    respiration INTEGER,
    spo2 INTEGER,
    ews_score INTEGER, -- feature 2
    risk_level TEXT,   -- feature 2: Stable, Watch, Critical
    recorded_at TIMESTAMP DEFAULT NOW()
);

-- 3. Add Timer Column to Patients (Feature 3)
ALTER TABLE patients ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP;
