<?php
// modules/ehr/certificate.php
require_once '../../includes/db.php';
require_once '../../includes/auth_session.php';
check_auth();

$role = get_user_role();
$page_title = "Medical Certificates";
include '../../includes/header.php';

$success = '';
$error = '';

// Handle Generation (Doctor)
if ($_SERVER['REQUEST_METHOD'] == 'POST' && $role === 'doctor') {
    $patient_id = $_POST['patient_id'];
    $type = $_POST['type'];
    $days = $_POST['days'];
    $diagnosis = $_POST['diagnosis'];
    $start_date = $_POST['start_date'];
    
    db_insert('medical_certificates', [
        'patient_id' => $patient_id,
        'doctor_id' => get_user_id(), // Should be staff ID, assuming user_id for simplicity or fetch staff
        'type' => $type,
        'start_date' => $start_date,
        'days' => $days,
        'diagnosis' => $diagnosis
    ]);
    $success = "Certificate generated.";
}

// Fetch Certificates
$certs = [];
if ($role === 'patient') {
    $patient = db_select_one("SELECT id FROM patients WHERE user_id = $1", [get_user_id()]);
    if ($patient) {
        $certs = db_select("SELECT * FROM medical_certificates WHERE patient_id = $1 ORDER BY created_at DESC", [$patient['id']]);
    }
} elseif ($role === 'doctor') {
    // Show recent certs generated by this doctor
    $certs = db_select("SELECT mc.*, p.first_name, p.last_name 
                        FROM medical_certificates mc 
                        JOIN patients p ON mc.patient_id = p.id 
                        ORDER BY mc.created_at DESC");
}

?>

<div class="card">
    <div class="card-header">Medical Certificates</div>
    <div class="card-body">
        <?php if ($success): ?><div class="alert alert-success"><?php echo $success; ?></div><?php endif; ?>

        <?php if ($role === 'doctor'): 
            $patients = db_select("SELECT id, first_name, last_name FROM patients ORDER BY last_name");
        ?>
            <div style="margin-bottom: 20px; padding: 15px; background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 5px;">
                <h5>Generate Certificate</h5>
                <form method="POST" action="" style="display: flex; gap: 10px; flex-wrap: wrap; align-items: flex-end;">
                    <div style="flex: 1; min-width: 200px;">
                        <label>Patient</label>
                        <select name="patient_id" class="form-control" required>
                            <option value="">-- Select Patient --</option>
                            <?php foreach ($patients as $p): ?>
                                <option value="<?php echo $p['id']; ?>"><?php echo htmlspecialchars($p['first_name'] . ' ' . $p['last_name']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div style="flex: 1; min-width: 150px;">
                        <label>Type</label>
                        <select name="type" class="form-control">
                            <option value="Sick Leave">Sick Leave</option>
                            <option value="Fitness Certificate">Fitness Certificate</option>
                        </select>
                    </div>
                    <div style="flex: 1; min-width: 150px;">
                        <label>Start Date</label>
                        <input type="date" name="start_date" class="form-control" value="<?php echo date('Y-m-d'); ?>" required>
                    </div>
                    <div style="flex: 1; min-width: 100px;">
                        <label>Days</label>
                        <input type="number" name="days" class="form-control" value="1" required>
                    </div>
                    <div style="flex: 2; min-width: 300px;">
                        <label>Diagnosis/Reason</label>
                        <input type="text" name="diagnosis" class="form-control" placeholder="e.g. Viral Fever" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Generate</button>
                </form>
            </div>
        <?php endif; ?>

        <table style="width: 100%; border-collapse: collapse;">
            <thead>
                <tr style="background: #f8f9fa; text-align: left;">
                    <th style="padding: 10px;">Date</th>
                    <?php if ($role !== 'patient'): ?><th style="padding: 10px;">Patient</th><?php endif; ?>
                    <th style="padding: 10px;">Type</th>
                    <th style="padding: 10px;">Details</th>
                    <th style="padding: 10px;">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($certs as $c): ?>
                    <tr style="border-bottom: 1px solid #eee;">
                        <td style="padding: 10px;"><?php echo date('M d, Y', strtotime($c['created_at'])); ?></td>
                        <?php if ($role !== 'patient'): ?>
                            <td style="padding: 10px;"><?php echo htmlspecialchars($c['first_name'] . ' ' . $c['last_name']); ?></td>
                        <?php endif; ?>
                        <td style="padding: 10px;"><?php echo htmlspecialchars($c['type']); ?></td>
                        <td style="padding: 10px;">
                            <?php echo htmlspecialchars($c['diagnosis']); ?> 
                            (<?php echo $c['days']; ?> days from <?php echo $c['start_date']; ?>)
                        </td>
                        <td style="padding: 10px;">
                            <button class="btn btn-sm" style="background: #6c757d; color: white;" onclick="window.print()">Print</button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include '../../includes/footer.php'; ?>
